### ISSUE TITLE
Установка 

### ISSUE THREAD

**Issue by shin0bi2014** [ITDSystems/alvex-orgchart#2]
Скомпилировал через еклипс amp, все без проблем. Залил на альфреску и установил через скрипт apply_amps.sh. 
получил следующие ошибки:
```
org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22._c_anonymous_1(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js:7)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22.call(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22._c_script_0(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js:8)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22.call(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22.call(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_web_extension_site_webscripts_components_orgchart_tree_view_orgchart_tree_view_get_js_22.exec(file:/opt/alfresco/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js)
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScriptImpl(JSScriptProcessor.java:333)
```

Сама альфреска загрузилась, появились дополнительные разделы в меню Люди и Мой профиль, но при нажатии на саму оргструктуру сыпятся данные ошибки. 
хотелось бы узнать мой конкретно косяк, или собирать его нужно конкретно через юникс консоль?

**Comment by ArgentumHeart** [comment]
Добрый день! Я добавил фикс на import, попробуйте ещё раз. Если проблема останется, то напишите какая у вас версия Alfresco и немного подробнее способ сборки и деплоя.

**Comment by aviriel** [comment]
Нет ответа уже 3 недели, видимо, все хорошо. Закрываю тикет.

**Comment by shin0bi2014** [comment]
извините не было оповещения, думал забыли про мою ошибку.
проверю
