### ISSUE TITLE
Не устанавливается Alvex Orgchart

### ISSUE THREAD

**Issue by code-911** [ITDSystems/alvex-orgchart#6]
Привет.

Ставил по инструкции: http://docs.alvexsoftware.com/ru-RU/Alvex/2.1/html-single/Admin_Guide/

Установил Alfresco Community (Build: 201602)
	- Alfresco Platform:	5.1.e
	- Alfresco Share: 5.1.e

Запустил, остановил. Удалил каталоги  tomcat/webapps/alfresco и tomcat/webapps/share

Собрал из исходников *.amp -ы, переименовал в orgchart-1.1-repo.amp и orgchart-1.1-share.amp Скопировал в соответствующие каталоги, запустил  bin/apply_amps.sh, в списке модулей их увидел.

Запустил альфрезку, все стартует:

`$ ./alfresco.sh start
waiting for server to start.... done
server started
/store/program/alfresco-community/postgresql/scripts/ctl.sh : postgresql  started at port 5433
Using CATALINA_BASE:   /store/program/alfresco-community/tomcat
Using CATALINA_HOME:   /store/program/alfresco-community/tomcat
Using CATALINA_TMPDIR: /store/program/alfresco-community/tomcat/temp
Using JRE_HOME:        /store/program/alfresco-community/java
Using CLASSPATH:       /store/program/alfresco-community/tomcat/bin/bootstrap.jar:/store/program/alfresco-community/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /store/program/alfresco-community/tomcat/temp/catalina.pid
Tomcat started.
/store/program/alfresco-community/tomcat/scripts/ctl.sh : tomcat started`

Но share не работает. Обращение в http://localhost:8085/share/ (томкат на 8085) выдает:

`HTTP Status 404 - /share/`

В логе alfresco-community/share.log такое:

`2016-08-24 14:51:00,608 ERROR [org.springframework.web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alvex-orgchart' defined in file [/store/program/alfresco-community/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/alvex-orgchart-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:995)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:265)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1261)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1542)
	at com.alvexcore.share.ShareExtension.afterPropertiesSet(ShareExtension.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	... 25 more`

Прошу помощи.

**Comment by aviriel** [comment]
Установите utils из репозитория alvex-common, они требуются по зависимостям.

**Comment by code-911** [comment]
Подскажите как это сделать?

**Comment by code-911** [comment]
Выковырнул из orgchart-1.1-share.amp /libs жарник utils-1.1-installable.jar. Это оно? Как его установить?

**Comment by aviriel** [comment]
Соберите orgchart из репозитория https://github.com/ITDSystems/alvex-meta, все зависимости подтянутся сами.
Но на данный момент в orgchart присутствует баг, который позволяет развернуть оргстурктуру из скрипта импорта, но не позволяет ее создать через админку (#5). Подождите вторника, этот баг будет решен.

**Comment by code-911** [comment]
Спасибо, склонировал  https://github.com/ITDSystems/alvex-meta, пробую собрать:

`alvex-meta$ mvn clean package`

мавен не собирает, не видит модулей:

`[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-common/utils/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-custom-workflows/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-uploader/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-project-management/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-common/utils/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-custom-workflows/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-uploader/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
[ERROR] Child module /home/medved/work/project/heddo/alvex-meta/alvex-project-management/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.alvexcore:alvex-meta:1.1 (/home/medved/work/project/heddo/alvex-meta/pom.xml) has 10 errors
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-common/utils/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-custom-workflows/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-uploader/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-project-management/repo of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-common/utils/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-custom-workflows/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-uploader/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR]     Child module /home/medved/work/project/heddo/alvex-meta/alvex-project-management/share of /home/medved/work/project/heddo/alvex-meta/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException`
 
Версия maven: 3.3.9

**Comment by aviriel** [comment]
@fufler, можешь сделать инструкцию по сборке временную? Подмодули оказались не очевидны даже для тех, кто часто использует github.

**Comment by fufler** [comment]
@code-911, какой командой клонировали репозиторий? Что выдаёт команда git submodule?

**Comment by code-911** [comment]
Клонировал: git clone https://github.com/ITDSystems/alvex-meta.git

Забыл похоже сделать (с субмодулями не работал): 

git submodule init
git submodule update

Сейчас результат mvn clean package такой:


`mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Alvex orgchart component [Repo]
[INFO] Alvex orgchart component [Share]
[INFO] Alvex
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alvex orgchart component [Repo] 1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ orgchart ---
[INFO] Deleting /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-sdk-requirements) @ orgchart ---
[INFO] 
[INFO] --- alfresco-maven-plugin:2.2.0:set-version (default-set-version) @ orgchart ---
[INFO] Added timestamp to version - 1.1.1608251147
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-test-resource (add-env-test-properties) @ orgchart ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ orgchart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo/src/main/resources
[INFO] Copying 138 resources to /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo/target/amp
[INFO] 
[INFO] --- alfresco-maven-plugin:2.2.0:refresh (refresh-webscripts-repo-and-share) @ orgchart ---
[WARNING] Connection failed to localhost:8080, null webapp refresh aborted
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ orgchart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/medved/work/project/heddo/alvex-meta/alvex-orgchart/repo/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Alvex orgchart component [Repo] .................... FAILURE [  2.843 s]
[INFO] Alvex orgchart component [Share] ................... SKIPPED
[INFO] Alvex .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.243 s
[INFO] Finished at: 2016-08-25T11:47:34+03:00
[INFO] Final Memory: 26M/324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project orgchart: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by fufler** [comment]
> git submodule init
git submodule update

Либо так, либо нужно использовать `git clone --recursive`.

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project orgchart: Fatal error compiling: invalid target release: 1.8

Что говорит javac -version?

**Comment by code-911** [comment]
```
$ javac -version
javac 1.8.0_77
```

**Comment by fufler** [comment]
Могу предположить, что что-то не так с установкой mvn или java. Судя по всему maven пытается собирать при помощи компилятора из другой JDK. Предлагаю проверить, какие версии JDK стоят и собрать при помощи той, которая поддерживает Java 8.

**Comment by code-911** [comment]
Да, так и есть, собиралось jdk7, спасибо.
Собрал через jdk8
Остановил аьфреско
Удалил tomcat/webapps/alfresco и tomcat/webapps/share
Скопировал alvex-meta/alvex-orgchat/share/target/orgchart-1.1.amp в alfresco-community/amps_share
Скопировал alvex-meta/alvex-orgchat/repo/target/orgchart-1.1.amp в в alfresco-community/amps
Выполнил bin/apply_amps.sh
Запустил альфреско

Результат тот же (share.log):

`2016-08-25 14:40:41,601 ERROR [org.springframework.web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alvex-orgchart' defined in file [/store/program/alfresco-community/tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension/alvex-orgchart-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:995)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:265)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1261)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1542)
	at com.alvexcore.share.ShareExtension.afterPropertiesSet(ShareExtension.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	... 25 more`

В чем может быть проблема?

**Comment by code-911** [comment]
Не следует ли мне установить в альфрезку и

alvex-meta/alvex-common/utils/repo/target/utils-1.1.amp
alvex-meta/alvex-common/utils/share/target/utils-1.1.amp

?

**Comment by code-911** [comment]
Попробовал, не помогло. Попробовал проделать все то же на другом компьютере, результат такой же (

**Comment by code-911** [comment]
Друзья. Так как же мне все же заставить работать alvex-orgchart?

**Comment by fufler** [comment]
@code-911, если ещё актуально, то инструкцию по сборке можно почитать [здесь](https://github.com/ITDSystems/alvex#build).
